/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTopicTopicIdRouteImport } from './routes/_authenticated/topic.$topicId'
import { Route as AuthenticatedResultAttemptIdRouteImport } from './routes/_authenticated/result.$attemptId'
import { Route as AuthenticatedQuizTopicIdRouteImport } from './routes/_authenticated/quiz.$topicId'
import { Route as AuthenticatedOnboardingVarkRouteImport } from './routes/_authenticated/onboarding.vark'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTopicTopicIdRoute =
  AuthenticatedTopicTopicIdRouteImport.update({
    id: '/topic/$topicId',
    path: '/topic/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultAttemptIdRoute =
  AuthenticatedResultAttemptIdRouteImport.update({
    id: '/result/$attemptId',
    path: '/result/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizTopicIdRoute =
  AuthenticatedQuizTopicIdRouteImport.update({
    id: '/quiz/$topicId',
    path: '/quiz/$topicId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingVarkRoute =
  AuthenticatedOnboardingVarkRouteImport.update({
    id: '/onboarding/vark',
    path: '/onboarding/vark',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/onboarding/vark': typeof AuthenticatedOnboardingVarkRoute
  '/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/onboarding/vark': typeof AuthenticatedOnboardingVarkRoute
  '/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/_authenticated/onboarding/vark': typeof AuthenticatedOnboardingVarkRoute
  '/_authenticated/quiz/$topicId': typeof AuthenticatedQuizTopicIdRoute
  '/_authenticated/result/$attemptId': typeof AuthenticatedResultAttemptIdRoute
  '/_authenticated/topic/$topicId': typeof AuthenticatedTopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/courses/$slug'
    | '/onboarding/vark'
    | '/quiz/$topicId'
    | '/result/$attemptId'
    | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/courses/$slug'
    | '/onboarding/vark'
    | '/quiz/$topicId'
    | '/result/$attemptId'
    | '/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/courses'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/courses/$slug'
    | '/_authenticated/onboarding/vark'
    | '/_authenticated/quiz/$topicId'
    | '/_authenticated/result/$attemptId'
    | '/_authenticated/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/topic/$topicId': {
      id: '/_authenticated/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof AuthenticatedTopicTopicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/result/$attemptId': {
      id: '/_authenticated/result/$attemptId'
      path: '/result/$attemptId'
      fullPath: '/result/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$topicId': {
      id: '/_authenticated/quiz/$topicId'
      path: '/quiz/$topicId'
      fullPath: '/quiz/$topicId'
      preLoaderRoute: typeof AuthenticatedQuizTopicIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/vark': {
      id: '/_authenticated/onboarding/vark'
      path: '/onboarding/vark'
      fullPath: '/onboarding/vark'
      preLoaderRoute: typeof AuthenticatedOnboardingVarkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedOnboardingVarkRoute: typeof AuthenticatedOnboardingVarkRoute
  AuthenticatedQuizTopicIdRoute: typeof AuthenticatedQuizTopicIdRoute
  AuthenticatedResultAttemptIdRoute: typeof AuthenticatedResultAttemptIdRoute
  AuthenticatedTopicTopicIdRoute: typeof AuthenticatedTopicTopicIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedOnboardingVarkRoute: AuthenticatedOnboardingVarkRoute,
  AuthenticatedQuizTopicIdRoute: AuthenticatedQuizTopicIdRoute,
  AuthenticatedResultAttemptIdRoute: AuthenticatedResultAttemptIdRoute,
  AuthenticatedTopicTopicIdRoute: AuthenticatedTopicTopicIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
